/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ethereum_test_jni_CCallJava */

#ifndef _Included_ethereum_test_jni_CCallJava
#define _Included_ethereum_test_jni_CCallJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ethereum_test_jni_CCallJava
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ethereum_test_jni_CCallJava_callbackAdd
  (JNIEnv *, jobject);

/*
 * Class:     ethereum_test_jni_CCallJava
 * Method:    callbackHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ethereum_test_jni_CCallJava_callbackHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     ethereum_test_jni_CCallJava
 * Method:    callbackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ethereum_test_jni_CCallJava_callbackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     ethereum_test_jni_CCallJava
 * Method:    callbackSayHell
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ethereum_test_jni_CCallJava_callbackSayHell
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
